### ISSUE TITLE
   print(f'do_GET {self.path}')  SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by muktabirajdar** [OpenAgInitiative/python-wifi-connect#12]
I m new to python .i installed python-wifi-connect.whenever i run i m getting print(f'do_GET {self.path}')  SyntaxError: invalid syntax. if anyone knows the answer.please do reply.

**Comment by srmoore** [comment]
Which version of python are you using? python-wifi-connect is compatible with python 3.

**Comment by muktabirajdar** [comment]
python 3.7 in raspberry pi 3

**Comment by srmoore** [comment]
Can you give me a little more information:
What command are you using to start the program?

Can you post the output of python --version ?

The f string is valid syntax and should work with python 3.7.
I have a Raspberry pi 3 here, and will see if I can reproduce, but I have a feeling that however you are starting python-wifi-connect it is actually using python 2.x rather than 3.

**Comment by muktabirajdar** [comment]
Thank for your reply, it's working fine now, python default version was set
to 2.7

**Comment by srmoore** [comment]
Glad you got it to work!
